# Generated by Django 5.1 on 2025-01-09 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_chat_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'verbose_name': 'Чат', 'verbose_name_plural': 'Чаты'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
