services:

  frontend:
    build:
      context: internet-store-frontend/
      dockerfile: Dockerfile
    ports:
      - '5173:5173'

  postgres:
    image: postgres
    env_file:
      - ./.env
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]

  redis:
    image: redis/redis-stack:latest
    ports:
       - "8001:8001"
       - "6379:6379"
    volumes:
      - redis_volume:/data

  backend:
    build:
      context: ./internet-store-backend
      dockerfile: Dockerfile
    ports:
      - '8000:8000'

    env_file:
      - ./.env
    environment:
      POSTGRES_HOST: postgres
      REDIS_HOST: redis

    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"   # Для HTTP
      # - "443:443" # Для HTTPS
    depends_on:
      - frontend
      - backend

volumes:
  redis_volume: {}
  pgdata: {}
  pgadmin_volume:
