services:

  frontend:
    build:
      context: internet-store-frontend/
      dockerfile: Dockerfile
    ports:
      - '5173:5173'

  postgres:
    image: postgres
    env_file:
      - ./.env
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]

  redis:
    image: redis/redis-stack:latest
    ports:
       - "8001:8001"
       - "6379:6379"
    volumes:
      - redis_volume:/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8002:8002"
    volumes:
      - pgadmin_volume:/var/lib/pgadmin

    environment:
      - PGADMIN_DEFAULT_EMAIL=user@example.com
      - PGADMIN_DEFAULT_PASSWORD=12345
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False

    depends_on:
      - postgres

  backend:
    build:
      context: ./internet-store-backend
      dockerfile: Dockerfile
    ports:
      - '8000:8000'

    env_file:
      - ./.env
    environment:
      POSTGRES_HOST: postgres
      REDIS_HOST: redis

    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./internet-store-backend/internetStore/staticfiles:/app/staticfiles
    ports:
      - "80:80"   # Для HTTP
      # - "443:443" # Для HTTPS
    depends_on:
      - frontend
      - backend

  ngrok:
    image: ngrok/ngrok:latest
    network_mode: host
    container_name: ngrok
    expose:
      - 443
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    command: ["http", "--url=clear-precious-turkey.ngrok-free.app", "80"]
    depends_on:
      - nginx

  get_ngrok_url:
    build:
      context: ./ngrok
    container_name: get_ngrok_url
    entrypoint: ["sh", "-c", "sleep 10 && curl -s http://ngrok:4040/api/tunnels | jq -r '.tunnels[0].public_url'"]
    depends_on:
      - ngrok

volumes:
  redis_volume: {}
  pgdata: {}
  pgadmin_volume:
