# Generated by Django 5.1 on 2024-11-27 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('store', '0016_remove_orderitem_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat', to='store.order'),
        ),
    ]
