FROM curlimages/curl:latest

# Устанавливаем jq с правами суперпользователя
USER root
RUN apk add --no-cache jq

CMD echo "url website: https://clear-precious-turkey.ngrok-free.app/ url admin: https://clear-precious-turkey.ngrok-free.app/api/admin"
