# Generated by Django 5.1 on 2024-12-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_remove_orderitem_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='isDelivered',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('preparing', 'Собирается'), ('in_transit', 'В пути'), ('ready_for_pickup', 'Готово к выдаче')], default='preparing', max_length=20),
        ),
    ]
