# Generated by Django 5.1 on 2024-09-10 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_productheart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentheart',
            options={'verbose_name': 'Лайки для комментариев', 'verbose_name_plural': 'Лайк для комментария'},
        ),
        migrations.AlterModelOptions(
            name='reviewheart',
            options={'verbose_name': 'Лайк', 'verbose_name_plural': 'Лайки для отзыва'},
        ),
    ]
