# Generated by Django 5.1 on 2024-09-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='views',
            new_name='detailViews',
        ),
        migrations.AddField(
            model_name='product',
            name='fastViews',
            field=models.IntegerField(default=0),
        ),
    ]
