# Generated by Django 5.1 on 2024-09-23 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phoneNumber',
        ),
    ]
