# Generated by Django 5.1 on 2024-11-20 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('store', '0014_rename_images_product_mainimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='chat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='orders.chat'),
        ),
    ]
