# Generated by Django 5.1 on 2024-11-27 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_orderitem_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='chat',
        ),
    ]
